# Site settings
title: Narendran Thangarajan
email: firstname.lastname@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Building a better future, one step at a time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ntvita.com" # the base hostname & protocol for your site
twitter_username: naren_live
github_username:  narendran

# Build settings
markdown: kramdown
